### ISSUE TITLE
Send log line w/ trace

### ISSUE THREAD

**Issue by agardnerIT** [agardnerIT/tracepusher#17]
Add functionality to send a log line with the trace and span ID preset.

This means that backends should automatically be able to correlate the log line with the span.

# 1. Send Logs to Collector

```
curl -X POST http://1.2.3.4:4318/v1/logs \
-H "Content-Type: application/json" \
-d '{"resourceLogs":[{"resource":{"attributes":[{"key":"resource-attr","value":{"stringValue":"resource-attr-val-1"}}]},"scopeLogs":[{"scope":{},"logRecords":[{"timeUnixNano":"1581452773000000789","severityNumber":9,"severityText":"Info","name":"logA","body":{"stringValue":"This is a log message"},"attributes":[{"key":"app","value":{"stringValue":"server"}},{"key":"instance_num","value":{"intValue":"1"}}],"droppedAttributesCount":1,"traceId":"08040201000000000000000000000000","spanId":"0102040800000000"},{"timeUnixNano":"1581452773000000789","severityNumber":9,"severityText":"Info","name":"logB","body":{"stringValue":"something happened"},"attributes":[{"key":"customer","value":{"stringValue":"acme"}},{"key":"env","value":{"stringValue":"dev"}}],"droppedAttributesCount":1,"traceId":"","spanId":""}]}]}]}'
```

# 2. Have Collector Send Logs to Backend (eg. Loki)

From here: https://grafana.com/docs/opentelemetry/collector/send-logs-to-loki/loki-receiver/

```
exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

service:
  pipelines:
    logs:
      receivers: [loki]
      processors: [attributes]
      exporters: [loki]
```
